# Generated by Django 3.2 on 2022-06-16 17:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionData',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=255, unique=True)),
                ('institution_tin', models.CharField(max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('DRIVING_SCHOOL', 'DRIVING SCHOOL'), ('HIGH_SCHOOL', 'HIGH SCHOOL')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDepartment',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutiondata')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutiondata')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionJobTitle',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutiondepartment')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionEmployee',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255)),
                ('kra_pin', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('is_user', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutiondata')),
                ('job_title_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutionjobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='What the course Entails', max_length=255)),
                ('total_payable', models.IntegerField(help_text='Total amount of the course')),
                ('institution_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.institutiondata')),
            ],
        ),
    ]
