# Generated by Django 3.2 on 2022-06-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtsaCharges',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Prices Per NTSA Charge')),
            ],
        ),
    ]
